import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  landscape: {
    position: 'absolute',
    bottom: 0,
    width: '98%',
    height: 151,
    backgroundColor: '#4a9e3b',
    borderTopLeftRadius: 101,
    borderTopRightRadius: 102,
  },
  tree: {
    position: 'absolute',
    bottom: 30,
    width: 50,
    height: 70,
    backgroundColor: '#2e7d32',
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  tree1: { left: '20%' },
  tree2: { left: '30%', height: 50, width: 40 },
  tree3: { right: '20%' },
  card: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    width: '85%',
    marginBottom: 50,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  inputContainer: {
    width: '100%',
    alignItems: 'center',
  },
  input: {
    width: '100%',
    backgroundColor: '#f5f5f5',
    borderRadius: 10,
    padding: 15,
    marginBottom: 15,
    fontSize: 16,
    color: '#333',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  primaryButton: {
    backgroundColor: '#2e7d32',
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginVertical: 10,
    width: '100%',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
  },
  disabledButton: {
    backgroundColor: '#aaa',
    opacity: 0.7,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
    fontWeight: '600',
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginVertical: 15,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e0e0e0',
  },
  dividerText: {
    paddingHorizontal: 10,
    color: '#a0a0a0',
    fontWeight: 'bold',
  },
  secondaryButton: {
    paddingVertical: 10,
    width: '100%',
  },
  secondaryButtonText: {
    color: '#2e7d32',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '500',
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  logoCircle: {
    width: 80,
    height: 80,
    backgroundColor: 'white',
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  logoIcon: {
    fontSize: 40,
  },
  appName: {
    fontSize: 24,
    color: 'white',
    fontWeight: 'bold',
  },
});

export default styles;